apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: q3svcayush
  name: q3svcayush
spec:
  ports:
  - nodePort: 31565
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    adhoc: ayushq3
  type: NodePort
status:
  loadBalancer: {}
