apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: ayushq2
  name: q2podayush
spec:
  containers:
  - image: nginx
    name: q2podayush
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
