apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: q2svcayush
  name: q2svcayush
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    adhoc: ayushq2
  type: NodePort
status:
  loadBalancer: {}
